var aNavItemData = [
	[
		{
			url:'https://www.mi.com',
			img:'images/ph1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/ph4.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph4.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/el1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/el2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/el3.jpg',
			name:'小米MIX3',
			price:'3299元',
		},
		{
			url:'https://www.mi.com',
			img:'images/el4.png',
			name:'小米MIX3',
			price:'3299元',
		},
		{
			url:'https://www.mi.com',
			img:'images/el1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/el2.jpg',
			name:'小米MIX3',
			price:'3299元',
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/bijiben.png',
			name:'小米笔记本',
			price:'4999元',
		},
		{
			url:'https://www.mi.com',
			img:'images/bijiben.png',
			name:'小米笔记本',
			price:'4999元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/bijiben.png',
			name:'小米笔记本',
			price:'4999元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/bijiben.png',
			name:'小米笔记本',
			price:'4999元',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/kongtiao.jpg',
			name:'米家互联网空调（一级能效）',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/kongtiao.jpg',
			name:'米家互联网空调（一级能效）',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/kongtiao.jpg',
			name:'米家互联网空调（一级能效）',
			price:'3299元',
		},
		{
			url:'https://www.mi.com',
			img:'images/kongtiao.jpg',
			name:'米家互联网空调（一级能效）',
			price:'3299元',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/ph3.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'小米路由器4',
			price:'199元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'小米路由器4',
			price:'199元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'小米路由器4',
			price:'199元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'小米路由器4',
			price:'199元',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/ph3.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'https://www.mi.com',
			img:'images/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		}
	]
]

var aCateItemData = [
	[
		{
			url:'https://www.mi.com',
			img:'images/small1.jpg',
			name:'红米6X'
		},
		{
			url:'https://www.mi.com',
			img:'images/small2.png',
			name:'小米8'
		},
		{
			url:'https://www.mi.com',
			img:'images/small3.jpg',
			name:'米粉卡 日租卡'
		},
		{
			url:'https://www.mi.com',
			img:'images/small1.jpg',
			name:'红米6X'
		},
		{
			url:'https://www.mi.com',
			img:'images/small2.png',
			name:'小米8'
		},
		{
			url:'https://www.mi.com',
			img:'images/small3.jpg',
			name:'米粉卡 日租卡'
		},
		{
			url:'https://www.mi.com',
			img:'images/small1.jpg',
			name:'红米6X'
		},
		{
			url:'https://www.mi.com',
			img:'images/small2.png',
			name:'小米8'
		},
		{
			url:'https://www.mi.com',
			img:'images/small3.jpg',
			name:'米粉卡 日租卡'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/el1.jpg',
			name:'小米电视4A '
		},
		{
			url:'https://www.mi.com',
			img:'images/el2.jpg',
			name:'小米电视4A 32英寸'
		},
		{
			url:'https://www.mi.com',
			img:'images/el3.jpg',
			name:'小米电视4A 43英寸'
		},
		{
			url:'https://www.mi.com',
			img:'images/el4.png',
			name:'小米电视4A 50英寸'
		},{
			url:'https://www.mi.com',
			img:'images/el5.jpg',
			name:'小米电视4A 55英寸'
		},
		{
			url:'https://www.mi.com',
			img:'images/el2.jpg',
			name:'小米电视4A 58英寸'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/bijiben.png',
			name:'小米笔记本'
		},
		{
			url:'https://www.mi.com',
			img:'images/bijiben.png',
			name:'小米笔记本'
		},
		{
			url:'https://www.mi.com',
			img:'images/bijiben.png',
			name:'小米笔记本'
		},
		{
			url:'https://www.mi.com',
			img:'images/bijiben.png',
			name:'小米笔记本'
		},
		{
			url:'https://www.mi.com',
			img:'images/bijiben.png',
			name:'小米笔记本'
		},
		{
			url:'https://www.mi.com',
			img:'images/bijiben.png',
			name:'小米笔记本'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/kongtiao.jpg',
			name:'米家互联网空调'
		},
		{
			url:'https://www.mi.com',
			img:'images/kongtiao.jpg',
			name:'米家互联网空调'
		},
		{
			url:'https://www.mi.com',
			img:'images/kongtiao.jpg',
			name:'米家互联网空调'
		},
		{
			url:'https://www.mi.com',
			img:'images/kongtiao.jpg',
			name:'米家互联网空调'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'https://www.mi.com',
			img:'images/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'https://www.mi.com',
			img:'images/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'https://www.mi.com',
			img:'images/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'https://www.mi.com',
			img:'images/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'https://www.mi.com',
			img:'images/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'https://www.mi.com',
			img:'images/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'https://www.mi.com',
			img:'images/pinghengche.jpg',
			name:'平衡车'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'https://www.mi.com',
			img:'images/luyouqi.jpg',
			name:'路由器'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'https://www.mi.com',
			img:'images/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'https://www.mi.com',
			img:'images/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'https://www.mi.com',
			img:'images/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'https://www.mi.com',
			img:'images/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'https://www.mi.com',
			img:'images/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'https://www.mi.com',
			img:'images/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'https://www.mi.com',
			img:'images/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'https://www.mi.com',
			img:'images/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'https://www.mi.com',
			img:'images/yidongdianyuan.jpg',
			name:'移动电源'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'https://www.mi.com',
			img:'images/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'https://www.mi.com',
			img:'images/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'https://www.mi.com',
			img:'images/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'https://www.mi.com',
			img:'images/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'https://www.mi.com',
			img:'images/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'https://www.mi.com',
			img:'images/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'https://www.mi.com',
			img:'images/chuifengji.jpg',
			name:'吹风机'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/erji.jpg',
			name:'耳机'
		},
		{
			url:'https://www.mi.com',
			img:'images/erji.jpg',
			name:'耳机'
		},
		{
			url:'https://www.mi.com',
			img:'images/erji.jpg',
			name:'耳机'
		},
		{
			url:'https://www.mi.com',
			img:'images/erji.jpg',
			name:'耳机'
		},
		{
			url:'https://www.mi.com',
			img:'images/erji.jpg',
			name:'耳机'
		},
		{
			url:'https://www.mi.com',
			img:'images/erji.jpg',
			name:'耳机'
		},
		{
			url:'https://www.mi.com',
			img:'images/erji.jpg',
			name:'耳机'
		},
		{
			url:'https://www.mi.com',
			img:'images/erji.jpg',
			name:'耳机'
		}
	],
	[
		{
			url:'https://www.mi.com',
			img:'images/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'https://www.mi.com',
			img:'images/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'https://www.mi.com',
			img:'images/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'https://www.mi.com',
			img:'images/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'https://www.mi.com',
			img:'images/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'https://www.mi.com',
			img:'images/quwenqi.jpg',
			name:'驱蚊器'
		},{
			url:'https://www.mi.com',
			img:'images/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'https://www.mi.com',
			img:'images/quwenqi.jpg',
			name:'驱蚊器'
		}
	]
]

var aElecItemData = [
	[
		{
			url:'../mi-band/mi-band.html',
			img:'images/shouhuan.jpg',
			name:'小米手环3',
			desc:'及超薄机身/2GB+8GB',
			price:'166',
			del:'199',
		},
		{
			url:'',
			img:'images/el1.jpg',
			name:'小米电视4X 43英寸',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/el1.jpg',
			name:'小米电视4X 43英寸',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
		},
		{
			url:'',
			img:'images/el1.jpg',
			name:'小米电视4X 43英寸',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/el1.jpg',
			name:'小米电视4X 43英寸',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/el1.jpg',
			name:'小米电视4X 43英寸',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
		},
		{
			url:'',
			img:'images/el1.jpg',
			name:'小米电视4X 43英寸',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			top:{
				url:'',
				img:'images/hezi.jpg',
				name:'小米盒子',
				price:'199'
			},
			bottom:{
				url:'',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
	[
		{
			url:'',
			img:'images/el2.jpg',
			name:'小米电视',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/el2.jpg',
			name:'小米电视',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/el2.jpg',
			name:'小米电视',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/el2.jpg',
			name:'小米电视',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/el3.jpg',
			name:'小米电视',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/el3.jpg',
			name:'小米电视',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/el3.jpg',
			name:'小米电视',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			top:{
				url:'',
				img:'images/ca.png',
				name:'小米电视4X 43英寸',
				price:'3699',
			},
			bottom:{
				url:'',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
	[
		{
			url:'',
			img:'images/bijiben.png',
			name:'小米电脑',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/bijiben.png',
			name:'小米电脑',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/bijiben.png',
			name:'小米电脑',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/bijiben.png',
			name:'小米电脑',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/bijiben.png',
			name:'小米电脑',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/bijiben.png',
			name:'小米电脑',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/bijiben.png',
			name:'小米电脑',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			top:{
				url:'',
				img:'images/ca.png',
				name:'小米电视4X 43英寸',
				price:'3699',
			},
			bottom:{
				url:'',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
	[
		{
			url:'',
			img:'images/jiqiren.jpg',
			name:'小米扫地机器人',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/jiqiren.jpg',
			name:'小米扫地机器人',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/jiqiren.jpg',
			name:'小米扫地机器人',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/jiqiren.jpg',
			name:'小米扫地机器人',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/shoudiantong.jpg',
			name:'小米随身手电筒',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/shoudiantong.jpg',
			name:'小米随身手电筒',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'images/shoudiantong.jpg',
			name:'小米随身手电筒',
			desc:'及超薄机身/2GB+8GB',
			price:'3699',
			del:'4699',
			view:{
				recommend:'挺不错的，很酷的样子，非常nice',
				author:'yonghu'
			}
		},
		{
			top:{
				url:'',
				img:'images/ca.png',
				name:'小米电视4X 43英寸',
				price:'3699',
			},
			bottom:{
				url:'',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	]
]

var aQuestionData = [
	[
		{
			ques1:'小米账户如何注册？',
			ques2:'手机如何申诉解锁？',
			ques3:'什么是账号申诉重置密码保护？',
			ques4:'如何进行重置密码保护？',
			ques5:'小米账号忘记密码如何找回？',
			ques6:'如何认证小米社区VIP？'
		}
	],
	[
		{
			ques1:'缺货的产品什么时间能下单购买？',
			ques2:'为什么订单满150元还要支付快递费用？',
			ques3:'活动时赠送的产品可选吗？',
			ques4:'下单后多长时间发货？',
			ques5:'小米商城支持什么方式支付？',
			ques6:'为什么购物车中显示有货，去结算时无货？'
		}
	],
	[
		{
			ques1:' 如何修改订单发票？',
			ques2:' 如何修改订单？',
			ques3:' 如何取消订单？',
			ques4:' 优惠券如何使用？',
			ques5:' 如何查询物流信息？',
			ques6:' 小米产品如何辨别真伪？'
		}
	],
	[
		{
			ques1:' 在小米商城购买商品如何申请售后？',
			ques2:' 如何查询售后进度？',
			ques3:' 维修价格查询',
			ques4:' 如何查询维修网点？',
			ques5:' 小米售后服务政策',
			ques6:' 取消订单/退货后如何退款？'
		}
	],
	[
		{
			ques1:'小米账户如何注册？',
			ques2:'手机如何申诉解锁？',
			ques3:'什么是账号申诉重置密码保护？',
			ques4:'如何进行重置密码保护？',
			ques5:'小米账号忘记密码如何找回？',
			ques6:'如何认证小米社区VIP？'
		}
	],
	[
		{
			ques1:'缺货的产品什么时间能下单购买？',
			ques2:'为什么订单满150元还要支付快递费用？',
			ques3:'活动时赠送的产品可选吗？',
			ques4:'下单后多长时间发货？',
			ques5:'小米商城支持什么方式支付？',
			ques6:'为什么购物车中显示有货，去结算时无货？'
		}
	],
	[
		{
			ques1:' 如何修改订单发票？',
			ques2:' 如何修改订单？',
			ques3:' 如何取消订单？',
			ques4:' 优惠券如何使用？',
			ques5:' 如何查询物流信息？',
			ques6:' 小米产品如何辨别真伪？'
		}
	]
]